/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cfox_fxbspatchlib_FxBspatchNative */

#ifndef _Included_com_cfox_fxbspatchlib_FxBspatchNative
#define _Included_com_cfox_fxbspatchlib_FxBspatchNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cfox_fxbspatchlib_FxBspatchNative
 * Method:    bspatchFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cfox_fxbspatchlib_FxBspatchNative_bspatchFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
