/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cfox_fxjbsdiff_JBsdiff */

#ifndef _Included_com_cfox_fxjbsdiff_JBsdiff
#define _Included_com_cfox_fxjbsdiff_JBsdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cfox_fxjbsdiff_JBsdiff
 * Method:    diffFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cfox_fxjbsdiff_JBsdiff_diffFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
